version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nodejslambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fwleyjisngym"
s3_prefix = "nodejslambda"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
