version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ctm-as"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-htdogp53px59"
s3_prefix = "ctm-as"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"

